name: C CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src
      - name: checkout
        run: cd src
      - name: list
        run: ls && pwd
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
