name: Code Formatting

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  code-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: Run clang-format
      run: clang-format -i src/*.c src/*.h

    - name: Check if formatting is correct
      run: git diff --exit-code
